// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { DefaultParameters } from "./../../core_codegen/index.sol";

/**
 * @title IPix2048System
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPix2048System {
  function pix2048_Pix2048System_init() external;

  function pix2048_Pix2048System_interact(DefaultParameters memory default_parameters) external;

  function pix2048_Pix2048System_move(DefaultParameters memory default_parameters) external;
}
