// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Permissions, PermissionsData, PermissionsTableId } from "./tables/Permissions.sol";
import { Pixel, PixelData, PixelTableId } from "./tables/Pixel.sol";
import { PixelUpdate, PixelUpdateData, PixelUpdateTableId } from "./tables/PixelUpdate.sol";
import { QueueItem, QueueItemTableId } from "./tables/QueueItem.sol";
import { App, AppData, AppTableId } from "./tables/App.sol";
import { AppUser, AppUserTableId } from "./tables/AppUser.sol";
import { AppName, AppNameTableId } from "./tables/AppName.sol";
import { CoreActionAddress, CoreActionAddressTableId } from "./tables/CoreActionAddress.sol";
import { Instruction, InstructionTableId } from "./tables/Instruction.sol";
import { Snake, SnakeData, SnakeTableId } from "./tables/Snake.sol";
import { SnakeSegment, SnakeSegmentData, SnakeSegmentTableId } from "./tables/SnakeSegment.sol";
