// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Snake, SnakeData, SnakeTableId } from "./tables/Snake.sol";
import { SnakeSegment, SnakeSegmentData, SnakeSegmentTableId } from "./tables/SnakeSegment.sol";
