// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IQueueSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IQueueSystem {
  function queue_QueueSystem_process_queue(
    bytes32 id,
    uint256 timestamp,
    string memory name_space,
    string memory name,
    bytes calldata call_data
  ) external;
}
