// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */


/**
 * @title ISnakeSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISnakeSystem {


  function snake_SnakeSystem_move(address owner) external;


}
